spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_manager?characterEncoding=utf8mb4
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: INFO
